version: '2.2'

services:
  collabora:
    image: collabora/code:latest
    ports:
      # expose on tailscale using:
      # sudo tailscale serve https / localhost:9980
      # sudo tailscale funnel 443 on
      - '127.0.0.1:9980:9980'
    environment:
      # https://sdk.collaboraonline.com/docs/installation/Configuration.html
      aliasgroup1: "cloud\\.technat\\.ch"
      aliasgroup2: "nx38267\\.your-storageshare\\.de"
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host[0]=167.235.186.160"
      server_name: tevbox-55.little-cloud.ts.net
      DONT_GEN_SSL_CERT: 1
    cap_add:
      - MKNOD
    restart: always