app = "collabora-server"
primary_region = "cdg"

[build]
  image = "collabora/code:latest"

[deploy]
  strategy = "immediate"

[env]
	aliasgroup1="https://cloud.technat.ch:443"
  extra_params="--o:ssl.enable=false" 
  server_name="collabora-server.fly.dev"

[http_service]
  internal_port = 9980
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
