# fly.toml app configuration file generated for onlyoffice-docs on 2023-05-29T17:27:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "onlyoffice-docs"
primary_region = "cdg"
kill_timeout = 120

[build]
  image = "onlyoffice/documentserver:latest"

[deploy]
  strategy = "rolling"

[env]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
