# fly.toml app configuration file generated for collabora-online on 2023-10-03T14:56:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "collabora-online"
primary_region = "ams"
kill_timeout = "2m0s"

[build]
  image = "collabora/code:latest"

[deploy]
  strategy = "rolling"

[env]
  DONT_GEN_SSL_CERT = "1"
  aliasgroup1 = "cloud\\.technat\\.ch"
  aliasgroup2 = "nx38267\\.your-storageshare\\.de"
  aliasgroup3 = "cloud\\.js-buchsi\\.ch"
  aliasgroup4 = "nx42188\\.your-storageshare\\.de"
  server_name = "https://collabora-online.fly.dev"
  extra_params = '--o:ssl.enable=false --o:ssl.termination=true'


[[services]]
  internal_port = 9980
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000


[checks]
  [checks.ready]
    grace_period = "50s"
    interval = "5s"
    method = "get"
    path = "/"
    port = 9980
    timeout = "5s"
    type = "http"

# Prometheus metrics are exposed but need authentication
# But I don' want to set username/password for the admin interface
#[metrics]
#  port = 9980
#  path = "/cool/getMetrics" 